float Gamma : register( c0 );
sampler2D Texture : register( s0 );

struct PS_IN
{
	float2 texcoord : TEXCOORD;
	float4 texcoord1 : TEXCOORD1;
};

#include "../shared.h"

float4 main(PS_IN i) : COLOR
{
  if (!UI) discard;

	float4 o;

	float4 r0;
	float4 r1;
	float3 r2;
	r0.x = Gamma.x;
	r0.x = r0.x + -1;
	r1 = tex2D(Texture, i.texcoord);
	r1 = r1 * i.texcoord1;
	r0.yzw = r1.xyz;

	r2.xyz = max(r0.yzw, 0);
	r2.xyz = pow(r2.xyz, Gamma.x);

	o.xyz = (-abs(r0.x) >= 0) ? r1.xyz : r2.xyz;
	o.w = r1.w;

	return o;
}


/*

    ps_3_0
      0x000000B8:     def c1, -1, 9.99999975e-005, 0, 0
      0x000000D0:     dcl_texcoord v0.xy
      0x000000DC:     dcl_texcoord1 v1
      0x000000E8:     dcl_2d s0
   0  0x000000F4:     mov r0.x, c0.x
   1  0x00000100:     add r0.x, r0.x, c1.x
   2  0x00000110:     texld r1, v0, s0
   2  0x00000120:     mul r1, r1, v1
   3  0x00000130:     mov_sat r0.yzw, r1.xxyz
   4  0x0000013C:     max r2.xyz, r0.yzww, c1.y
   5  0x0000014C:     log r0.y, r2.x
   6  0x00000158:     log r0.z, r2.y
   7  0x00000164:     log r0.w, r2.z
   8  0x00000170:     mul r0.yzw, r0, c0.x
   9  0x00000180:     exp r2.x, r0.y
  10  0x0000018C:     exp r2.y, r0.z
  11  0x00000198:     exp r2.z, r0.w
  12  0x000001A4:     cmp oC0.xyz, -r0_abs.x, r1, r2
  13  0x000001B8:     mov oC0.w, r1.w

// approximately 15 instruction slots used (1 texture, 14 arithmetic)

//
// Generated by Microsoft (R) HLSL Shader Compiler 9.19.949.1104
//
// Parameters:
//
//   float Gamma;
//   sampler2D Texture;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Gamma        c0       1
//   Texture      s0       1
//




*/