// ---- Created with 3Dmigoto v1.3.16 on Thu Mar 05 16:36:33 2026

cbuffer _Globals : register(b0)
{
  float4 color : packoffset(c0);
  float length1 : packoffset(c1);
  float radius : packoffset(c1.y);
  float threshold : packoffset(c1.z);
  float4 dispersion : packoffset(c2);
}

SamplerState s_sampler_0_s : register(s0);
SamplerState s_sampler_1_s : register(s1);
Texture2D<float4> s_texture_0 : register(t0);
Texture2D<float4> s_texture_1 : register(t1);


// 3Dmigoto declarations
#define cmp -
#include "../shared.h"


void main(
  float4 v0 : SV_POSITION0,
  float2 v1 : TEXCOORD0,
  out float4 o0 : SV_TARGET0)
{
  float4 r0,r1,r2,r3,r4,r5,r6,r7;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xy = float2(0.5,0.5) + -v1.xy;
  r0.z = dot(r0.xy, r0.xy);
  r0.z = rsqrt(r0.z);
  r0.zw = r0.xy * r0.zz;
  r0.xyzw = length1 * r0.xyzw;
  r1.xy = r0.zw + r0.zw;
  r1.zw = r1.xy * dispersion.xx + v1.xy;
  r2.x = s_texture_1.Sample(s_sampler_1_s, r1.zw).y;
  r1.zw = s_texture_0.Sample(s_sampler_0_s, r1.zw).xw;
  r1.z = r1.z * r2.x;
  r1.w = saturate(-threshold + r1.w);
  r1.z = r1.z * r1.w;
  r2.xy = r0.zw * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.xy).y;
  r2.xy = s_texture_0.Sample(s_sampler_0_s, r2.xy).xw;
  r1.w = r2.x * r1.w;
  r2.x = saturate(-threshold + r2.y);
  r1.z = r1.w * r2.x + r1.z;
  r2.xy = r0.xy * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.xy).y;
  r2.xy = s_texture_0.Sample(s_sampler_0_s, r2.xy).xw;
  r1.w = r2.x * r1.w;
  r2.x = saturate(-threshold + r2.y);
  r1.z = r1.w * r2.x + r1.z;
  r2.xy = r0.xy + r0.xy;
  r2.zw = r2.xy * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r3.xyzw = float4(3,3,4,4) * r0.xyxy;
  r2.zw = r3.xy * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r2.zw = r3.zw * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r4.xyzw = float4(5,5,6,6) * r0.xyxy;
  r2.zw = r4.xy * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r2.zw = r4.zw * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r5.xyzw = float4(7,7,8,8) * r0.xyxy;
  r2.zw = r5.xy * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r2.zw = r5.zw * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r2.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).xw;
  r1.w = r2.z * r1.w;
  r2.z = saturate(-threshold + r2.w);
  r1.z = r1.w * r2.z + r1.z;
  r2.zw = float2(9,9) * r0.xy;
  r6.xy = r2.zw * dispersion.xx + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r6.xy).y;
  r6.xy = s_texture_0.Sample(s_sampler_0_s, r6.xy).xw;
  r1.w = r6.x * r1.w;
  r6.x = saturate(-threshold + r6.y);
  r6.x = r1.w * r6.x + r1.z;
  r1.zw = r0.zw * dispersion.yy + v1.xy;
  r0.zw = r0.zw * dispersion.zz + v1.xy;
  r6.w = s_texture_1.Sample(s_sampler_1_s, r1.zw).y;
  r1.zw = s_texture_0.Sample(s_sampler_0_s, r1.zw).yw;
  r1.z = r1.z * r6.w;
  r1.w = saturate(-threshold + r1.w);
  r7.xy = r1.xy * dispersion.yy + v1.xy;
  r1.xy = r1.xy * dispersion.zz + v1.xy;
  r6.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r6.w = r7.x * r6.w;
  r7.x = saturate(-threshold + r7.y);
  r6.w = r7.x * r6.w;
  r1.z = r1.z * r1.w + r6.w;
  r7.xy = r0.xy * dispersion.yy + v1.xy;
  r0.xy = r0.xy * dispersion.zz + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r2.xy * dispersion.yy + v1.xy;
  r2.xy = r2.xy * dispersion.zz + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r3.xy * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r3.zw * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r4.xy * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r4.zw * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r5.xy * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r5.zw * dispersion.yy + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r1.z = r1.w * r6.w + r1.z;
  r7.xy = r2.zw * dispersion.yy + v1.xy;
  r2.zw = r2.zw * dispersion.zz + v1.xy;
  r1.w = s_texture_1.Sample(s_sampler_1_s, r7.xy).y;
  r7.xy = s_texture_0.Sample(s_sampler_0_s, r7.xy).yw;
  r1.w = r7.x * r1.w;
  r6.w = saturate(-threshold + r7.y);
  r6.y = r1.w * r6.w + r1.z;
  r1.z = s_texture_1.Sample(s_sampler_1_s, r1.xy).y;
  r1.xy = s_texture_0.Sample(s_sampler_0_s, r1.xy).zw;
  r1.x = r1.x * r1.z;
  r1.y = saturate(-threshold + r1.y);
  r1.x = r1.x * r1.y;
  r1.y = s_texture_1.Sample(s_sampler_1_s, r0.zw).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r0.zw).zw;
  r0.z = r0.z * r1.y;
  r0.w = saturate(-threshold + r0.w);
  r0.z = r0.z * r0.w + r1.x;
  r0.w = s_texture_1.Sample(s_sampler_1_s, r0.xy).y;
  r0.xy = s_texture_0.Sample(s_sampler_0_s, r0.xy).zw;
  r0.x = r0.x * r0.w;
  r0.y = saturate(-threshold + r0.y);
  r0.x = r0.x * r0.y + r0.z;
  r0.y = s_texture_1.Sample(s_sampler_1_s, r2.xy).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r2.xy).zw;
  r0.y = r0.z * r0.y;
  r0.z = saturate(-threshold + r0.w);
  r0.x = r0.y * r0.z + r0.x;
  r0.yz = r3.xy * dispersion.zz + v1.xy;
  r1.xy = r3.zw * dispersion.zz + v1.xy;
  r0.w = s_texture_1.Sample(s_sampler_1_s, r0.yz).y;
  r0.yz = s_texture_0.Sample(s_sampler_0_s, r0.yz).zw;
  r0.y = r0.y * r0.w;
  r0.z = saturate(-threshold + r0.z);
  r0.x = r0.y * r0.z + r0.x;
  r0.y = s_texture_1.Sample(s_sampler_1_s, r1.xy).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r1.xy).zw;
  r0.y = r0.z * r0.y;
  r0.z = saturate(-threshold + r0.w);
  r0.x = r0.y * r0.z + r0.x;
  r0.yz = r4.xy * dispersion.zz + v1.xy;
  r1.xy = r4.zw * dispersion.zz + v1.xy;
  r0.w = s_texture_1.Sample(s_sampler_1_s, r0.yz).y;
  r0.yz = s_texture_0.Sample(s_sampler_0_s, r0.yz).zw;
  r0.y = r0.y * r0.w;
  r0.z = saturate(-threshold + r0.z);
  r0.x = r0.y * r0.z + r0.x;
  r0.y = s_texture_1.Sample(s_sampler_1_s, r1.xy).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r1.xy).zw;
  r0.y = r0.z * r0.y;
  r0.z = saturate(-threshold + r0.w);
  r0.x = r0.y * r0.z + r0.x;
  r0.yz = r5.xy * dispersion.zz + v1.xy;
  r1.xy = r5.zw * dispersion.zz + v1.xy;
  r0.w = s_texture_1.Sample(s_sampler_1_s, r0.yz).y;
  r0.yz = s_texture_0.Sample(s_sampler_0_s, r0.yz).zw;
  r0.y = r0.y * r0.w;
  r0.z = saturate(-threshold + r0.z);
  r0.x = r0.y * r0.z + r0.x;
  r0.y = s_texture_1.Sample(s_sampler_1_s, r1.xy).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r1.xy).zw;
  r0.y = r0.z * r0.y;
  r0.z = saturate(-threshold + r0.w);
  r0.x = r0.y * r0.z + r0.x;
  r0.y = s_texture_1.Sample(s_sampler_1_s, r2.zw).y;
  r0.zw = s_texture_0.Sample(s_sampler_0_s, r2.zw).zw;
  r0.y = r0.z * r0.y;
  r0.z = saturate(-threshold + r0.w);
  r6.z = r0.y * r0.z + r0.x;
  o0.xyz = color.xyz * r6.xyz * SI.lens_flare;
  o0.w = 1;
  return;
}