// ---- Created with 3Dmigoto v1.3.16 on Tue Nov 25 17:26:36 2025

cbuffer _Globals : register(b0)
{
  float bDecompressSceneColor : packoffset(c0);
  float InverseGamma : packoffset(c0.y);
}



// 3Dmigoto declarations
#define cmp -
#include "../shared.h"


void main(
  float4 v0 : COLOR0,
  float4 v1 : COLOR1,
  out float4 o0 : SV_Target0)
{
  if (!CUSTOM_IS_UI) discard;
  float4 r0;
  uint4 bitmask, uiDest;
  float4 fDest;

  r0.xyz = saturate(v0.xyz);
  r0.xyz = log2(r0.xyz);
  r0.xyz = InverseGamma * r0.xyz;
  o0.xyz = exp2(r0.xyz);
  o0.w = v1.w * v0.w;
  return;
}

/*
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.20789
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   bool bDecompressSceneColor;        // Offset:    0 Size:     4 [unused]
//   float InverseGamma;                // Offset:    4 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// COLOR                    1   xyzw        1     NONE   float      w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[1], immediateIndexed
      0x0000001C: dcl_input_ps linear v0.xyzw
      0x00000028: dcl_input_ps linear v1.w
      0x00000034: dcl_output o0.xyzw
      0x00000040: dcl_temps 1
   0  0x00000048: mov_sat r0.xyz, v0.xyzx
   1  0x0000005C: log r0.xyz, r0.xyzx
   2  0x00000070: mul r0.xyz, r0.xyzx, cb0[0].yyyy
   3  0x00000090: exp o0.xyz, r0.xyzx
   4  0x000000A4: mul o0.w, v0.w, v1.w
   5  0x000000C0: ret 
// Approximately 6 instruction slots used
*/