#include "./common.hlsl"


//
// Decompiled from:
//   mov_0x02D73469.ps_5_1.asm
//   Generated by Microsoft (R) HLSL Shader Compiler 10.1
//   Pixel Shader 5.1
//
// This shader decodes a planar YCbCr (YUV) video frame into RGB output.
// The three planes (Y, Cr, Cb) are stored in separate 2D textures.
// A colour-matrix transform converts YCbCr -> linear RGB, then a
// gamma curve (power 2.2) is applied before writing to the render target.
//

// ---------------------------------------------------------------------------
// Constant Buffer
// ---------------------------------------------------------------------------

cbuffer VideoConstants : register(b2, space0)
{
    float4 videoScale;           // offset  0  – per-plane UV scale: .xy for Y, .zw for CrCb
    float4 videoAlphaMul;        // offset 16  – per-channel output multiplier (and alpha)
    float4 videoCrc;             // offset 32  – Cr (red-difference) colour-matrix column
    float4 videoCrb;             // offset 48  – Cb (blue-difference) colour-matrix column
    float4 videoAdj;             // offset 64  – brightness/bias adjustment added after matrix
    float4 videoYScale;          // offset 80  – Y (luma) colour-matrix column
    float  videoGammaAdjustment; // offset 96  [unused in this shader]
};

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

SamplerState g_linear  : register(s7, space0);
Texture2D    videoYTex : register(t0, space0);   // luma   plane  (Y)
Texture2D    videoCRTex: register(t1, space0);   // chroma plane  (Cr / red-difference)
Texture2D    videoCBTex: register(t2, space0);   // chroma plane  (Cb / blue-difference)

// ---------------------------------------------------------------------------
// Input / Output
// ---------------------------------------------------------------------------

struct PS_INPUT
{
    float4 pos : SV_Position;   // v0 – not used in shader body
    float2 uv  : TEXCOORD0;     // v1.xy – normalised texture coordinates
};

struct PS_OUTPUT
{
    float4 colour : SV_Target0;
};

// ===========================================================================
// Main
// ===========================================================================
PS_OUTPUT main(PS_INPUT input)
{
    PS_OUTPUT output;

    float4 r0, r1;

    // -----------------------------------------------------------------------
    // Scale UVs separately for the luma and chroma planes.
    //   The luma plane may be full-resolution while the chroma planes are
    //   half-resolution (e.g. YCbCr 4:2:0 / 4:2:2), so videoScale provides
    //   independent scale factors for each.
    //
    //   mul r0.xyzw, v1.xyxy, CB0[2][0].xyzw
    //     r0.xy = input.uv * videoScale.xy   -> luma   UV
    //     r0.zw = input.uv * videoScale.zw   -> chroma UV
    // -----------------------------------------------------------------------
    r0 = input.uv.xyxy * videoScale;   // r0.xy = luma UV,  r0.zw = chroma UV

    // -----------------------------------------------------------------------
    // Sample each planar texture.
    //   The swizzle on the sample instructions re-routes the desired channel
    //   into the destination component (the textures store the value in R).
    //
    //   sample r0.x, r0.xyxx, T0[0].xyzw, S0[7]   -> Y  into r0.x
    //   sample r0.y, r0.zwzz, T1[1].yxzw, S0[7]   -> Cr into r0.y  (.yxzw swaps R->y dest)
    //   sample r0.z, r0.zwzz, T2[2].yzxw, S0[7]   -> Cb into r0.z  (.yzxw routes R->z dest)
    // -----------------------------------------------------------------------
    r0.x = videoYTex .Sample(g_linear, r0.xy).x;   // Y  luma sample
    r0.y = videoCRTex.Sample(g_linear, r0.zw).x;   // Cr chroma sample  (swizzle .yxzw -> r into .y)
    r0.z = videoCBTex.Sample(g_linear, r0.zw).x;   // Cb chroma sample  (swizzle .yzxw -> r into .z)

    // -----------------------------------------------------------------------
    // YCbCr -> RGB colour matrix
    //
    //   The three constant-buffer columns represent the contribution of each
    //   YCbCr component to the output RGB triplet:
    //
    //     rgb = videoYScale * Y  +  videoCrc * Cr  +  videoCrb * Cb  +  videoAdj
    //
    //   Assembly sequence:
    //     mul  r1.xyz,  r0.y,    videoCrc.xyz     -> Cr column * Cr
    //     mad  r0.xyw,  videoYScale.xyz, r0.x, r1.xyz  -> + Y column * Y
    //     mad  r0.xyz,  videoCrb.xyz,    r0.z,  r0.xyw -> + Cb column * Cb
    //     add  r0.xyz,  r0.xyz,  videoAdj.xyz    -> + bias/adjustment
    // -----------------------------------------------------------------------
    r1.xyz = r0.yyy * videoCrc.xyz;                          // Cr contribution
    r0.xyw = videoYScale.xyz * r0.xxx + r1.xyz;             // + Y  contribution  (note: .xyw maps to rgb)
    r0.xyz = videoCrb.xyz   * r0.zzz + r0.xyw;             // + Cb contribution
    r0.xyz = r0.xyz + videoAdj.xyz;                         // + brightness/bias adjustment

    // -----------------------------------------------------------------------
    // Set alpha to 1.0 (fully opaque before the per-channel multiplier)
    //   mov r0.w, 1.0
    // -----------------------------------------------------------------------
    r0.w = 1.0f;

    // -----------------------------------------------------------------------
    // Apply per-channel output multiplier (handles alpha scaling, HDR scaling,
    // or colour correction baked into videoAlphaMul).
    //   mul r0.xyzw, r0.xyzw, videoAlphaMul
    // -----------------------------------------------------------------------
    r0 = r0 * videoAlphaMul;

    // r0.xyz = mul(DCIP3_To_BT2020, r0.xyz);

    // -----------------------------------------------------------------------
    // Apply gamma 2.2 encoding:  out = |r0| ^ 2.2
    //
    //   The three-instruction sequence (max -> log -> mul -> exp) computes a
    //   power function while guarding against negative/zero inputs.
    //
    //   max  r0.xyzw, |r0.xyzw|, 0    -> clamp to non-negative (abs then max)
    //   log  r0.xyzw, r0.xyzw         -> ln(r0)
    //   mul  r0.xyzw, r0.xyzw, 2.2    -> 2.2 * ln(r0)
    //   exp  o0.xyzw, r0.xyzw         -> e^(2.2*ln(r0)) = r0^2.2
    // -----------------------------------------------------------------------
    r0      = max(abs(r0), 0.0f);           // guard: take absolute value, clamp to >= 0
    r0      = log(r0);                      // natural log
    r0      = r0 * (2.2f + (SI.gamma_correction <= 0.f ? 0.f : SI.gamma_correction - 2.f));                    // scale exponent
    output.colour = exp(r0);               // raise to power 2.2  ->  gamma-encoded output

    return output;
}